"""Handles .tsx single-file and .zip multi-file export of generated Angular components."""

import zipfile
import io
from core.validator import extract_block


def extract_blocks(component_code: str) -> dict[str, str]:
    """Extract ts, html, css sections from generated component string."""
    ts = extract_block(component_code, "// component.ts", "// component.html")
    html = extract_block(component_code, "// component.html", "// component.css")
    css_marker = "// component.css"
    css_start = component_code.find(css_marker)
    css = component_code[css_start + len(css_marker):].strip() if css_start != -1 else ""
    return {"ts": ts, "html": html, "css": css}


def export_tsx(component_code: str, filename: str = "component") -> bytes:
    """Bundle all three blocks into a single .tsx file. Returns UTF-8 bytes."""
    blocks = extract_blocks(component_code)
    content = (
        "// Generated by Guided Component Architect\n"
        "// TypeScript + HTML template + CSS combined for export.\n\n"
        "// === TYPESCRIPT ===\n"
        f"{blocks['ts']}\n\n"
        "// === HTML TEMPLATE ===\n"
        "/*\n"
        f"{blocks['html']}\n"
        "*/\n\n"
        "// === CSS ===\n"
        "/*\n"
        f"{blocks['css']}\n"
        "*/"
    )
    # RULE 6: explicit UTF-8 encoding — never rely on OS default
    return content.encode("utf-8")


def export_zip(component_code: str, tokens: dict, filename: str = "component") -> bytes:
    """Bundle ts/html/css + design-tokens.md into an in-memory zip. Returns bytes."""
    blocks = extract_blocks(component_code)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{filename}.component.ts", blocks["ts"])
        zf.writestr(f"{filename}.component.html", blocks["html"])
        zf.writestr(f"{filename}.component.css", blocks["css"])
        token_md = "# Design Tokens\n\n| Token | Value |\n|---|---|\n"
        for k, v in tokens.items():
            token_md += f"| {k} | {v} |\n"
        zf.writestr("design-tokens.md", token_md)
    buf.seek(0)
    return buf.read()
